#!/bin/bash
cd `dirname $0`
param=$1
config=~/.dhere
if [ ! -d $config ];
then
    mkdir $config
    # cp ./readme.md $config/readme.md

fi

desktopHere(){
    path=$1
    cat $config/password.txt | sudo -S rm -r ~/Desktop
    ln -s $path ~/Desktop
    
}

backup(){
    time=`date "+%Y_%m_%d_%H_%M_%S"`
    path=$config/_Desktop_$time
    mkdir $path
    cp -r ~/Desktop/ $path
    # find ~/Desktop/  | xargs -i mv {} $path
    desktopHere $path
}

authenticate(){
    if [ ! -e $config/password.txt ];
    then
        read -s -p "please enter your password:" password
        echo $password > $config/password.txt
    fi
}

authenticate


if [[ $param == --reset ]]||[[ $param == -r ]];
then
    echo ==================================
    ls -a .dhere | grep '_Desktop_.'|sort
    echo ==================================
    read -p 'please enter your desktop version:' Desktopbackup
    
    while [ ! -d $destpath];
    do
        read -p 'please try again:' Desktopbackup 
        destpath=$config/$Desktopbackup 
    done
    desktopHere $destpath

elif [[ $param == --drop ]]||[[ $param == -d ]];
then
    rm -r ~/Desktop
    mkdir ~/Desktop

elif [[ $param == --list ]]||[[ $param == -l ]];
then
    echo ==================================
    echo list history versions
    ls -a .dhere | grep '_Desktop_.'|sort
    echo ==================================

elif [[ $param == --backup ]]||[[ $param == -b ]];
then
    echo ==================================
    echo store current desktop
    backup
    echo ==================================

elif [[ $param == --help ]]||[[ $param == -h ]]||[[ $param == "" ]];
then
    more $config/readme.md
else
    if [ -d $param ];
    then
        desktopHere $param
    else
        echo "please check your directory"
    fi
fi