#!/bin/bash
param=$1
originlink=`readlink /usr/local/bin/dhere`
workspace=${originlink%%/dhere*}
if [[ workspace == '' ]];
then
    workspace=.
fi
config=$workspace/.dhere
if [ ! -d $config ];
then
    mkdir $config
    # cp ./readme.md $config/readme.md

fi

desktopHere(){
    path=$1
    cat $config/password.txt | sudo -S rm -r ~/Desktop
    ln -s $path ~/Desktop
    
}

backup(){
    time=`date "+%Y_%m_%d_%H_%M_%S"`
    path=$config/_Desktop_$time
    mkdir $path
    cp -r ~/Desktop/ $path
    # find ~/Desktop/  | xargs -i mv {} $path
    desktopHere $path
}

authenticate(){
    if [ ! -e $config/password.txt ];
    then
        read -s -p "please enter your password:" password
        echo $password > $config/password.txt
    fi
}

authenticate

if [[ $param == --reset ]]||[[ $param == -r ]];
then
    echo ==================================
    ls -a $workspace/.dhere | grep '_Desktop_.'|sort
    echo ==================================
    read -p 'please enter your desktop version:' Desktopbackup
    
    while [ ! -d $destpath];
    do
        read -p 'please try again:' Desktopbackup  
        destpath=$config/$Desktopbackup
    done
    destpath=$config/$Desktopbackup
    desktopHere $destpath

elif [[ $param == --drop ]]||[[ $param == -d ]];
then
    rm -r ~/Desktop
    mkdir ~/Desktop

elif [[ $param == --list ]]||[[ $param == -l ]];
then
    echo ==================================
    echo list history versions
    ls -a $workspace/.dhere | grep '_Desktop_.'|sort
    echo ==================================

elif [[ $param == --backup ]]||[[ $param == -b ]];
then
    echo ==================================
    echo store current desktop
    backup
    echo ==================================

elif [[ $param == --show ]]||[[ $param == -s ]];
then
    echo ==================================
    echo current desktop folder:
    result=`readlink ~/Desktop`
    if [[ $result == '' ]];
    then
        echo Default Desktop
    fi
    echo ==================================

elif [[ $param == --help ]]||[[ $param == -h ]]||[[ $param == "" ]];
then
    more $workspace/readme.md
else
    if [ -d $param ];
    then
        desktopHere $param
    else
        echo "please check your directory"
    fi
fi